import type {Metadata} from "next";
import {JetBrains_Mono, Roboto_Slab} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {Toaster} from "@/components/ui/sonner";
import {TRPCReactProvider} from "@/trpc/client";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});

const jetbrainsMonoHeading = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-heading",
});

export const metadata: Metadata = {
  title: "FlowForge",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "dark",
        "antialiased",
        robotoSlab.variable,
        jetbrainsMonoHeading.variable,
      )}
    >
    <body className="flex min-h-full flex-col">
    <TRPCReactProvider>
      {children}
    </TRPCReactProvider>
    <Toaster/>
    </body>
    </html>
  );
}
