import type { CreateProductInput } from "./product.schema.js";

const ph = (label: string) => `https://placehold.co/800x600/png?text=${encodeURIComponent(label)}`;

export const productSeedDocs: CreateProductInput[] = [
  {
    name: "Classic Wooden Building Blocks - 100 Piece Set",
    description:
      "A rainbow of smooth, sanded wooden blocks for stacking towers, castles, and bridges. Great for fine motor skills, spatial reasoning, and open-ended creative play. Pieces store neatly in a sturdy wooden crate.",
    category: "building-blocks",
    ageGroup: "3-5",
    price: 34.99,
    stock: 48,
    brand: "Melissa & Doug",
    material: "Wood",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.7,
    tags: ["wood", "stem", "open-ended"],
    images: [ph("Wooden Blocks")],
    isActive: true,
  },
  {
    name: "Magnetic Tiles Builder Set - 72 Pieces",
    description:
      "Strong magnets and vibrant translucent tiles click together for castles, rockets, and geometric sculptures. Encourages engineering thinking and collaborative building while staying easy for small hands to connect.",
    category: "building-blocks",
    ageGroup: "3-5",
    price: 59.99,
    stock: 32,
    brand: "Magna-Tiles",
    material: "Plastic",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.8,
    tags: ["magnets", "stem", "building"],
    images: [ph("Magnetic Tiles")],
    isActive: true,
  },
  {
    name: "Snuggly Teddy Bear Plush - Large",
    description:
      "Ultra-soft plush teddy with embroidered eyes and a huggable body made for bedtime stories and quiet comfort. Machine washable cover makes it parent-friendly while staying cozy for everyday adventures.",
    category: "soft-toys",
    ageGroup: "0-2",
    price: 24.5,
    stock: 60,
    brand: "GUND",
    material: "Polyester plush",
    color: "Brown",
    safetyCertified: true,
    rating: 4.6,
    tags: ["plush", "bedtime", "comfort"],
    images: [ph("Teddy Bear")],
    isActive: true,
  },
  {
    name: "Kids Floor Puzzle - Safari Animals 48pc",
    description:
      "Oversized pieces perfect for little hands to assemble a bright safari scene. Builds patience, pattern recognition, and teamwork as kids work together to complete the big picture on the living room floor.",
    category: "puzzles",
    ageGroup: "3-5",
    price: 16.99,
    stock: 74,
    brand: "Ravensburger",
    material: "Cardboard",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.5,
    tags: ["puzzle", "animals", "floor-puzzle"],
    images: [ph("Puzzle")],
    isActive: true,
  },
  {
    name: "Turbo Drift Remote Control Car",
    description:
      "Responsive 2.4GHz controls, spring suspension, and grippy tires for indoor races and smooth pavement runs. Includes rechargeable battery pack so the fun keeps going after school and on weekends.",
    category: "remote-control",
    ageGroup: "6-8",
    price: 42.0,
    stock: 22,
    brand: "BEZGAR",
    material: "Plastic",
    color: "Red",
    safetyCertified: true,
    rating: 4.3,
    tags: ["rc", "vehicles", "outdoor"],
    images: [ph("RC Car")],
    isActive: true,
  },
  {
    name: "Rainbow Art Coloring Kit - 120 Supplies",
    description:
      "Markers, crayons, colored pencils, and sticker sheets in a portable organizer for rainy-day creativity. Washable formulas help keep tables tidy while kids explore color blending and storytelling through drawings.",
    category: "art-craft",
    ageGroup: "6-8",
    price: 28.75,
    stock: 55,
    brand: "Crayola",
    material: "Mixed",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.6,
    tags: ["art", "markers", "creativity"],
    images: [ph("Art Kit")],
    isActive: true,
  },
  {
    name: "Pretend Play Doctor Set with Carry Case",
    description:
      "Stethoscope, thermometer, syringe toy, bandages, and patient cards spark caring role-play. Durable pieces fit into a compact case so cleanup is quick and pretend checkups can travel to grandma’s house.",
    category: "pretend-play",
    ageGroup: "3-5",
    price: 21.49,
    stock: 40,
    brand: "Kidzlane",
    material: "Plastic",
    color: "Blue",
    safetyCertified: true,
    rating: 4.4,
    tags: ["role-play", "doctor", "imagination"],
    images: [ph("Doctor Set")],
    isActive: true,
  },
  {
    name: "Alphabet Learning Board - Magnetic Letters",
    description:
      "Double-sided board with uppercase and lowercase magnets helps kids practice spelling simple words. Bright illustrations keep attention high while caregivers guide phonics and letter recognition at the kitchen table.",
    category: "educational-toys",
    ageGroup: "3-5",
    price: 19.99,
    stock: 63,
    brand: "LeapFrog",
    material: "Plastic",
    color: "Yellow",
    safetyCertified: true,
    rating: 4.5,
    tags: ["letters", "phonics", "learning"],
    images: [ph("Alphabet Board")],
    isActive: true,
  },
  {
    name: "Rainbow Stacking Rings with Wobbling Base",
    description:
      "Smooth rings slide onto a rocking post that adds a gentle challenge for motor control. Contrasting textures and cheerful colors support early sensory exploration during tummy time and seated play.",
    category: "educational-toys",
    ageGroup: "0-2",
    price: 14.25,
    stock: 88,
    brand: "Fisher-Price",
    material: "Plastic",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.7,
    tags: ["stacking", "motor-skills", "baby"],
    images: [ph("Stacking Rings")],
    isActive: true,
  },
  {
    name: "Outdoor Ball Set - Soccer, Basketball, Football",
    description:
      "Three lightweight balls sized for kids make park days and driveway games easy to start. Textured surfaces help small hands grip while encouraging active play and coordination with siblings and friends.",
    category: "outdoor-toys",
    ageGroup: "6-8",
    price: 26.0,
    stock: 35,
    brand: "Franklin Sports",
    material: "Rubber",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.2,
    tags: ["sports", "active-play", "outdoor"],
    images: [ph("Ball Set")],
    isActive: true,
  },
  {
    name: "Toy Kitchen Playset with Lights & Sounds",
    description:
      "Mini stove, sink, oven, and storage shelves with clicking knobs and sizzling sound effects invite restaurant role-play. Compact footprint fits bedrooms while still leaving room for pots, pans, and pretend ingredients.",
    category: "pretend-play",
    ageGroup: "3-5",
    price: 79.99,
    stock: 18,
    brand: "Step2",
    material: "Plastic",
    color: "Gray",
    safetyCertified: true,
    rating: 4.5,
    tags: ["kitchen", "pretend", "role-play"],
    images: [ph("Toy Kitchen")],
    isActive: true,
  },
  {
    name: "Dinosaur Figure Pack - 12 Species",
    description:
      "Detailed, kid-safe figures spanning T-Rex, Triceratops, Stegosaurus, and more for prehistoric adventures. Sturdy PVC holds up to sandbox digs, shelf displays, and classroom dino sorting activities.",
    category: "pretend-play",
    ageGroup: "6-8",
    price: 22.95,
    stock: 50,
    brand: "Schleich",
    material: "PVC",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.6,
    tags: ["dinosaurs", "figures", "collectibles"],
    images: [ph("Dinosaur Pack")],
    isActive: true,
  },
  {
    name: "Soft Bunny Plush with Floppy Ears",
    description:
      "Cloud-soft bunny with long ears and a bean-weighted bottom sits upright on shelves and laps. Gentle pastel tones make it a sweet gift for Easter baskets or comforting companions during travel naps.",
    category: "soft-toys",
    ageGroup: "0-2",
    price: 17.5,
    stock: 70,
    brand: "Jellycat",
    material: "Polyester plush",
    color: "Cream",
    safetyCertified: true,
    rating: 4.8,
    tags: ["plush", "bunny", "gift"],
    images: [ph("Soft Bunny")],
    isActive: true,
  },
  {
    name: "Junior STEM Experiment Kit - 20 Projects",
    description:
      "Safe chemistry and physics activities with step cards teach density, circuits, and simple machines. Adult-guided experiments keep mess manageable while kids build confidence as young scientists at home.",
    category: "educational-toys",
    ageGroup: "9-12",
    price: 44.99,
    stock: 27,
    brand: "National Geographic Kids",
    material: "Mixed",
    color: "Blue",
    safetyCertified: true,
    rating: 4.4,
    tags: ["stem", "science", "experiments"],
    images: [ph("STEM Kit")],
    isActive: true,
  },
  {
    name: "Shape Sorter Cube with Sliding Lid",
    description:
      "Chunky shapes and matching holes strengthen problem solving and hand-eye coordination. Sliding top makes dump-and-repeat play fast so toddlers stay engaged during independent play sessions.",
    category: "educational-toys",
    ageGroup: "0-2",
    price: 15.99,
    stock: 92,
    brand: "Melissa & Doug",
    material: "Wood",
    color: "Multicolor",
    safetyCertified: true,
    rating: 4.6,
    tags: ["shapes", "sorting", "toddler"],
    images: [ph("Shape Sorter")],
    isActive: true,
  },
];
